pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
    stage('Parallel Stage Build') {
            parallel {
                stage('Maven build') {
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test -Dmaven.test.failure.ignore=true'
            }
            post {
                success {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
            
                }
            }
          stage('Mock build')
                    stages{
                        stage('Dummy build'){
                            steps{
                                // Testing for parallel
                            }
                        }
                    }
            }
            }
    }
}
